# Minimal Cloud Build config that runs the Spring Boot Maven build-image goal
# This runs the project's Maven wrapper (if present) and uses Spring Boot's buildpacks
# to create and publish an image. The image is set to gcr.io/$PROJECT_ID/spring-petclinic:$SHORT_SHA
steps:
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # run the maven wrapper if present, otherwise fall back to mvn
        if [ -f mvnw ]; then
          chmod +x mvnw
          ./mvnw -B -DskipTests \
            -Dspring-boot.build-image.imageName=gcr.io/$PROJECT_ID/spring-petclinic:$SHORT_SHA \
            -Dspring-boot.build-image.publish=true \
            spring-boot:build-image
        else
          mvn -B -DskipTests \
            -Dspring-boot.build-image.imageName=gcr.io/$PROJECT_ID/spring-petclinic:$SHORT_SHA \
            -Dspring-boot.build-image.publish=true \
            spring-boot:build-image
        fi

# Declare the produced image so Cloud Build registers it
images:
  - 'gcr.io/$PROJECT_ID/spring-petclinic:$SHORT_SHA'


options:
  logging: CLOUD_LOGGING_ONLY
